# Generated by Django 5.0.1 on 2024-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_asset',
            name='Ddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='it_asset',
            name='purchasedate',
            field=models.DateField(null=True),
        ),
    ]
