# Generated by Django 5.0.1 on 2024-07-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_alter_it_asset_ddate_alter_it_asset_purchasedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_asset',
            name='value',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
