# Generated by Django 5.0.1 on 2024-08-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_alter_it_asset_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assetcat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
