# Generated by Django 5.0.1 on 2024-08-12 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_assetcat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset',
            new_name='assetname',
        ),
    ]
