# Generated by Django 5.0.1 on 2024-08-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_assetcat_desc_alter_assetname_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.assetname'),
        ),
    ]
