# Generated by Django 5.0.1 on 2024-08-12 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_alter_dashboard_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetname',
            name='ascat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.assetcat'),
        ),
    ]
