# Generated by Django 5.0.1 on 2024-08-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_assetname_ascat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetname',
            name='ascat',
        ),
    ]
