# Generated by Django 5.0.1 on 2024-08-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_remove_assetname_ascat'),
    ]

    operations = [
        migrations.CreateModel(
            name='manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
