# Generated by Django 5.0.1 on 2024-08-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_manufacturer_vendor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
