# Generated by Django 5.0.1 on 2024-08-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_rename_manufacturer_manufacture'),
    ]

    operations = [
        migrations.CreateModel(
            name='wrnty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('desc', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
