# Generated by Django 5.0.1 on 2024-08-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_wrnty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='it_asset',
            name='assetID',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
