# Generated by Django 5.0.1 on 2024-08-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_alter_it_asset_assetid'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_id', models.CharField(max_length=50, null=True)),
                ('monitor_id', models.CharField(max_length=50, null=True, unique=True)),
                ('sec_monitor_id', models.CharField(max_length=50, null=True)),
                ('project', models.CharField(max_length=50, null=True)),
                ('emp_id', models.CharField(max_length=50, null=True)),
                ('shift', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
