# Generated by Django 5.0.1 on 2024-08-13 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_userlist_emp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdata',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='empdata',
            name='project',
        ),
    ]
